Attempt to fix `'NoneType' object is not iterable`
```
2021-08-09 10:00:39 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{% set unavailable = namespace(entities=[], devices={}) %} {% set unavailable.entities = state_attr('sensor.unavailable_entities', 'entities') %}{% for entity in unavailable.entities %} {%   set device = device_id(entity) %} {%   if device is not none %} {%     if device not in unavailable.devices %} {%  set unavailable.devices = dict(unavailable.devices, **{ device: [] }) %} {% endif %} {%     set unavailable.devices = dict(unavailable.devices, **{ device: unavailable.devices[device] + [entity] }) %} {%   endif %} {% endfor %}{{ unavailable.devices | list }}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 393, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1398, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 2, in top-level template code
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 509, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 395, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: 'NoneType' object is not iterable
```