Revert "Use SNTP as a time source"
This reverts commit 6f55b66d46eb6e5ebbc38ba29bb4f1decfaa33c8.

```
Linking /data/office_desk/.pioenvs/office_desk/firmware.elf
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/office_desk/.pioenvs/office_desk/src/main.o:(.literal._Z5setupv+0xac): undefined reference to `vtable for esphome::sntp::SNTPComponent'
collect2: error: ld returned 1 exit status
*** [/data/office_desk/.pioenvs/office_desk/firmware.elf] Error 1
```